---
- name: Instalar IIS en Windows 10 Pro
  hosts: windows_vmware
  gather_facts: false

  tasks:
    - name: Descargar el instalador de IIS
      ansible.windows.win_get_url:
        url: "https://aka.ms/iisexpress_amd64_en-US.msi"
        dest: C:\Windows\Temp\iisexpress_amd64_en-US.msi

    - name: Instalar IIS usando win_package
      ansible.windows.win_package:
        path: C:\Windows\Temp\iisexpress_amd64_en-US.msi
        state: present
        