---
- name: Windows Server Patching
  hosts: win_server
  gather_facts: false
  
  tasks:
    - name: Gather Windows facts
      win_facts:

    - name: Install Windows Updates
      win_updates:
        category_names:
          - SecurityUpdates
          - UpdateRollups
          - CriticalUpdates
        state: installed
      register: update_result

    - name: Reboot if updates are installed
      win_reboot:
      when: update_result.reboot_required

    - name: Wait for the server to come back online
      wait_for_connection:
        timeout: 300
      when: update_result.reboot_required