---
- name: Actualizar paquetes en RHEL 9.4 con yum update --nobest
  hosts: rhel_vmware
  become: true
  
  tasks:
    - name: Actualizar todos los paquetes a la última versión disponible sin elegir la mejor opción
      ansible.builtin.shell: yum update --nobest -y
      register: yum_update_result
      ignore_errors: yes

    - name: Mostrar resultado de la actualización
      ansible.builtin.debug:
        var: yum_update_result
    
    - name: Verificar si se requiere reinicio
      ansible.builtin.command: needs-restarting -r
      register: needs_restarting_result
      changed_when: False
      failed_when: False

    - name: Reiniciar el servidor si es necesario
      ansible.builtin.reboot:
        msg: "Reiniciando servidor después de la actualización"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30
      when: needs_restarting_result.rc == 1

    - name: Esperar a que el servidor esté disponible de nuevo
      ansible.builtin.wait_for_connection:
        timeout: 300
      when: needs_restarting_result.rc == 1