---
- name: Deploy CentOS VM on VMware Workstation
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Create VM directory
      file:
        path: /path/to/vm_directory
        state: directory

    - name: Copy CentOS ISO to VM directory
      copy:
        src: 'C:\Users\jose.vargas\Downloads\CentOS-Stream-10-latest-x86_64-dvd1.iso'
        dest: 'C:\Users\jose.vargas\Downloads\CentOS-Stream-10-latest-x86_64-dvd1.iso'
        remote_src: yes

    - name: Create VMX file
      copy:
        dest: /path/to/vm_directory/CentOS.vmx
        content: |
          .encoding = "UTF-8"
          config.version = "8"
          virtualHW.version = "18"
          numvcpus = "2"
          memsize = "6144"
          ide0:0.present = "TRUE"
          ide0:0.fileName = "CentOS.iso"
          ide0:0.deviceType = "cdrom-image"
          ethernet0.present = "TRUE"
          ethernet0.connectionType = "nat"
          displayName = "CentOS VM"
          guestOS = "centos-64"
          scsi0:0.present = "TRUE"
          scsi0:0.fileName = "CentOS.vmdk"
          scsi0:0.deviceType = "disk"
          scsi0:0.virtualDev = "lsilogic"

    - name: Create VMDK disk file
      command: vmware-vdiskmanager -c -s 20GB -a lsilogic -t 1 /path/to/vm_directory/CentOS.vmdk

    - name: Run VM
      command: vmrun -T ws start /path/to/vm_directory/CentOS.vmx nogui
