- name: Crear una máquina virtual en VMware Workstation 17 Player (Windows)
  hosts: windows
  tasks:

    - name: Crear directorio para la VM
      win_file:
        path: "C:\\Users\\Public\\Documents\\VMware\\CentOS_Stream_VM"
        state: directory

    - name: Copiar plantilla base VMX
      win_copy:
        src: "C:\\Users\\Public\\Documents\\VMware\\templates\\centos_template.vmx"
        dest: "C:\\Users\\Public\\Documents\\VMware\\CentOS_Stream_VM\\CentOS_Stream.vmx"

    - name: Modificar configuración de la VM (RAM y CPU)
      win_shell: |
        (Get-Content "C:\Users\Public\Documents\VMware\CentOS_Stream_VM\CentOS_Stream.vmx") -replace 'memsize = "\d+"', 'memsize = "6144"' | Set-Content "C:\Users\Public\Documents\VMware\CentOS_Stream_VM\CentOS_Stream.vmx"
        (Get-Content "C:\Users\Public\Documents\VMware\CentOS_Stream_VM\CentOS_Stream.vmx") -replace 'numvcpus = "\d+"', 'numvcpus = "1"' | Set-Content "C:\Users\Public\Documents\VMware\CentOS_Stream_VM\CentOS_Stream.vmx"

    - name: Crear disco virtual de 20GB
      win_shell: |
        "C:\Program Files (x86)\VMware\VMware Workstation\vmware-vdiskmanager.exe" -c -s 20GB -a lsilogic -t 0 "C:\Users\Public\Documents\VMware\CentOS_Stream_VM\CentOS_Stream.vmdk"

    - name: Adjuntar disco virtual a la VM
      win_shell: |
        (Get-Content "C:\Users\Public\Documents\VMware\CentOS_Stream_VM\CentOS_Stream.vmx") + "`r`nscsi0:0.fileName = `"`"CentOS_Stream.vmdk`"`"" | Set-Content "C:\Users\Public\Documents\VMware\CentOS_Stream_VM\CentOS_Stream.vmx"

    - name: Configurar ISO de instalación de CentOS Stream
      win_shell: |
        (Get-Content "C:\Users\Public\Documents\VMware\CentOS_Stream_VM\CentOS_Stream.vmx") + "`r`nide1:0.present = `"`"TRUE`"`"" | Set-Content "C:\Users\Public\Documents\VMware\CentOS_Stream_VM\CentOS_Stream.vmx"
        (Get-Content "C:\Users\Public\Documents\VMware\CentOS_Stream_VM\CentOS_Stream.vmx") + "`r`nide1:0.fileName = `"`"C:\Users\Public\Downloads\CentOS-Stream.iso`"`"" | Set-Content "C:\Users\Public\Documents\VMware\CentOS_Stream_VM\CentOS_Stream.vmx"
        (Get-Content "C:\Users\Public\Documents\VMware\CentOS_Stream_VM\CentOS_Stream.vmx") + "`r`nide1:0.deviceType = `"`"cdrom-image`"`"" | Set-Content "C:\Users\Public\Documents\VMware\CentOS_Stream_VM\CentOS_Stream.vmx"
        (Get-Content "C:\Users\Public\Documents\VMware\CentOS_Stream_VM\CentOS_Stream.vmx") + "`r`nbios.bootOrder = `"`"cdrom`"`"" | Set-Content "C:\Users\Public\Documents\VMware\CentOS_Stream_VM\CentOS_Stream.vmx"

    - name: Iniciar la VM en VMware Workstation
      win_shell: |
        "C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" -T ws start "C:\Users\Public\Documents\VMware\CentOS_Stream_VM\CentOS_Stream.vmx" nogui
