---
- name: Crear archivo de lista de paquetes instalados en RHEL 9
  hosts: rhel_vmware
  become: yes

  tasks:
    - name: Obtener lista de paquetes instalados
      command: rpm -qa
      register: paquetes_instalados

    - name: Crear archivo de texto con la lista de paquetes
      copy:
        content: "{{ paquetes_instalados.stdout_lines | join('\n') }}"
        dest: /home/rhel_ansible/paquetes_instalados.txt