---
- name: Crear archivo de lista de paquetes instalados en RHEL 9
  hosts: rhel_vmware
  become: yes

  tasks:
    - name: Create a directory if it does not exist
      #nsible.builtin.file:
      file:
       path: /home/rhel_ansible/reporte1
       state: directory
      #mode: '0755'

    - name: Obtener lista de paquetes instalados
      command: rpm -qa
      register: paquetes_instalados

    - name: Crear archivo de texto con la lista de paquetes
      copy:
        content: "{{ paquetes_instalados.stdout_lines | join('\n') }}"
        dest: /home/rhel_ansible/reporte1/paquetes_instalados.txt