---
- name: Instalar y configurar MariaDB en CentOS Stream
  hosts: centosprueba1
  become: yes

  tasks:
    - name: Habilitar el módulo de MariaDB en AppStream
      command: dnf module enable mariadb -y

    - name: Instalar MariaDB Server
      yum:
        name: mariadb-server
        state: present

    - name: Habilitar y arrancar el servicio MariaDB
      service:
        name: mariadb
        state: started
        enabled: yes

    - name: Crear base de datos de prueba
      mysql_db:
        name: demo_db
        state: present

    - name: Crear usuario en MariaDB
      mysql_user:
        name: root
        password: "1234"
        priv: 'demo_db.*:ALL'
        state: present