---
- name: Instalar y configurar MariaDB
  hosts: centosprueba1
  become: yes

  tasks:
    - name: Instalar MariaDB
      yum:
        name: mariadb-server
        state: present

    - name: Asegurarse de que MariaDB esté habilitado y corriendo
      service:
        name: mariadb
        state: started
        enabled: yes

    - name: Configurar usuario y base de datos
      mysql_db:
        name: root
        state: present

    - name: Crear usuario en MariaDB
      mysql_user:
        name: root
        password: "1234"
        priv: 'demo_db.*:ALL'
        state: present