---
- name: Configuración de servidor MySQL
  hosts: centos_demo
  become: yes
  tasks:
    - name: Instalar MySQL
      yum:
        name: mysql-server
        state: present

    - name: Iniciar y habilitar el servicio MySQL
      systemd:
        name: mysqld
        state: started
        enabled: yes

    - name: Configurar la contraseña de root de MySQL
      mysql_user:
        name: root
        password: "tu_contraseña"
        host_all: yes
        state: present